import type { Metadata } from "next";
import Navbar from "./../components/Navbar";

import "./globals.css";
import Layout from "./../components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>
        <body>{children}</body>
      </Layout>
    </html>
  );
}
